- name: Play level variables
  hosts: localhost
  vars:
    URL: Play.example.com
  tasks:
    - name: printing play level variables
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: play for tasks level variables
  hosts: localhost
  tasks:
    - name: tasks level variables
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Play for vars from file
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: vars from file
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Play level vars
  hosts: localhost
  tasks:
    - name: vars from inventory file
      ansible.builtin.debug:
        msg: "{{ URL }}"
